import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./globalComponents/Navbar";
import Footer from "./globalComponents/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Food App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="h-screen bg-gray-100"><div className="bg-gray-100">
        <Navbar />
      </div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
