import { ClerkProvider } from '@clerk/nextjs';//added this line
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./globalComponents/Navbar";
import Footer from "./globalComponents/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Food App",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}>
      <html lang="en">
        <body>
        <div className="bg-[rgb(193,233,239)]">
        <Navbar />
      {children}
      <Footer />
      </div>
        </body>
    </html>
    </ClerkProvider>
  );
}
