import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./globalComponents/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Food App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="h-screen bg-blue-100"><div className="bg-blue-100">
        <Navbar />
      </div>
        {children}
      </body>
    </html>
  );
}
